all:	mgr client rep util


mgr:
	javac mgr/*.java
	javac mgr/info/*.java
	javac mgr/runnables/*.java
	javac mgr/lookuptable/*.java

client:
	javac client/*.java

rep:
	javac repository/*.java

util:
	javac util/*.java

